new post: _posts/2021-02-24-bash-rc-profile-exec-order.md

diff --git a/_bin/newpost b/_bin/newpost
--- a/_bin/newpost
+++ b/_bin/newpost
@@ -7,12 +7,12 @@ usage() {
 
 basedir=$(cd $(dirname $0) && pwd)
 
-cd $basedir/../_posts || {
-    echo "cannot find project home"
-    exit 1
-}
 
 new() {
+    cd $basedir/../_posts || {
+        echo "cannot find project home"
+        exit 1
+    }
     local dt=$(date '+%F')
     if [[ -n $1 ]]; then
         local pre=$(echo "$1"|awk -F'-' '{print $1}')
@@ -56,7 +56,7 @@ post() {
         f=$postname.md
     fi
     if ! [ -f $f ]; then
-        echo "cannot find post"
+        echo "cannot find post $f"
         return 1
     fi
     git add $f
